version: '3'

services:
  app:
    container_name: allsell-back
    build:
      context: ./
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
